### ISSUE TITLE
SetContent(IHtmlContent content) should be renamed to SetHtmlContent

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/HtmlAbstractions#18]
We changed the `Append` overloads to be specific on whether they were appending HTML or non-HTML content. Aka `AppendHtml` had an overload for `IHtmlContent` but `Append` did not.

We need to make this same change to `SetContent`/`SetHtmlContent`.

**Comment by Eilon** [comment]
Either we change in RC2 or never. No strong opinion either way.

**Comment by NTaylorMullen** [comment]
Lets change this in RC2 then.
