### ISSUE TITLE
Should rename `IHtmlContentBuilder.Append(IHtmlContent)` to `IHtmlContentBuilder.AppendHtml(IHtmlContent)`

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/HtmlAbstractions#4]
This is a pre-requisite to [this](https://github.com/aspnet/Razor/issues/634) issue and has the same reasoning. Essentially it's already decently confusing when determining how to append encoded/unencoded content. This would help make it clearer since `IHtmlContent` is HTML.

**Comment by hishamco** [comment]
IMHO Append is make since while it's a member of ```IHtmlContentBuilder``` unless we can append non-html content

**Comment by dougbu** [comment]
The language here is never going to be quite right. An `IHtmlContent` implementation may or may not be pre-encoded. And, while `IHtmlContent` is intended to write out HTML content, that should be obvious from the instance type; why repeat that inference in this particular method name?
