### ISSUE TITLE
UrlEncoding with TextEncoding

### ISSUE THREAD

**Issue by cilerler** [aspnet/HtmlAbstractions#46]
I have a text that retrieved from the web and saved into a file with encoding 1252.

Text has URL's in it with some emoji's. However unless I get the result from method1 below, I can not be able to retrieve those pages.

Since we don't have System.Web in dotnet-core and no support from System.Net.WebUtility for TextEncoding,

I wonder, if you may provide me a simple example how to achieve this via new UrlEncoder.

```
var text = "hello-world ðŸ’Ÿ";

Encoding sourceEncoding = Encoding.GetEncoding(1252);

// method 1 // hello-world+%f0%9f%92%9f // <----- result, I would like to get
System.Web.HttpUtility.UrlEncode(text, sourceEncoding).Dump();

// method 2 // hello-world+%c3%b0%c5%b8%e2%80%99%c5%b8
System.Web.HttpUtility.UrlEncode(text).Dump();                                                              

// method 3 // hello-world+%C3%B0%C5%B8%E2%80%99%C5%B8
System.Net.WebUtility.UrlEncode(text).Dump();                                                               

// method 4 // hello-world%20%C3%B0%C5%B8%E2%80%99%C5%B8
System.Uri.EscapeUriString(text).Dump();  
```

Thanks in advance 🤗

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#23500
